### PR TITLE
adding-achlioptas-point-generator

### PR DESCRIPTION
**Pull request by optas**

### CODE REVIEW

**Comment by optas** [comment]
adding-achlioptas-point-generator

**Comment by timzhang642** [comment]
Thanks for the contribution, Panos. Just wanted to let you know that the link for code and image is broken.

**Comment by optas** [comment]
Hi Tim - Thanks a lot for the prompt reply. 
I had forgotten to make the repository (which includes the image) public. It should work now.
Keep the good job up!
Panos

**Comment by timzhang642** [comment]
Great work, Panos! Can't wait to read your paper.

**Comment by optas** [comment]
Thanks a lot Tim!
Have a good day.
Panos

On Dec 10, 2017, at 8:36 AM, Yuxuan (Tim) Zhang <notifications@github.com<mailto:notifications@github.com>> wrote:


Merged #2<https://github.com/timzhang642/3D-Machine-Learning/pull/2>.

**Pull request merged**
